name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/.cache/pip
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Check out code
        uses: actions/checkout@v3

      - uses: alexellis/setup-arkade@v2
      - uses: alexellis/arkade-get@master
        with:
          golangci-lint: latest

      - name: Lint Go Code
        run: |
          make lint-go

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/.cache/pip
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build binary, making sure it does compile
        run: |
          make build

