name: release

on:
  push:
    tags:
    - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: git fetch --prune --unshallow
    - uses: actions/setup-go@v4
      with:
        go-version: 1.19.x

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/.cache/pip
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashfiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - uses: goreleaser/goreleaser-action@v4.4.0
      with:
        version: latest
        args: release --timeout=60m --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        AUR_PRIVATE_KEY: ${{ secrets.AUR_PRIVATE_KEY }}
